//! Package artifact assembly: `.PKGINFO`, `.MTREE`, and the final tarball.
//!
//! Arch's package format is a tar archive whose first members are metadata:
//! `.PKGINFO` (key/value package metadata) then `.MTREE` (a gzipped mtree
//! listing used to verify installed files), followed by the payload rooted at
//! the filesystem root.
//!
//! Ownership: `std.tar.Writer` emits uid/gid 0 for every member, which is
//! exactly right here — Arch packages are uniformly root-owned, and any
//! non-root ownership is applied post-install by scriptlets. That also means
//! the archive step needs no fakeroot session of its own; fakeroot is required
//! only while `package()` runs so its `chown`/`install -o` calls succeed.

const std = @import("std");
const srcinfo = @import("srcinfo.zig");
const verify = @import("verify.zig");

pub const Error = error{EmptyPackage};

pub const Compression = enum {
    none,
    gzip,

    pub fn extension(c: Compression) []const u8 {
        return switch (c) {
            .none => ".pkg.tar",
            .gzip => ".pkg.tar.gz",
        };
    }
};

/// Everything needed to write a `.PKGINFO`.
pub const Meta = struct {
    pkgname: []const u8,
    pkgbase: []const u8,
    /// Full version, `[epoch:]pkgver-pkgrel`.
    version: []const u8,
    pkgdesc: []const u8 = "",
    url: []const u8 = "",
    arch: []const u8 = "x86_64",
    packager: []const u8 = "opti",
    builddate: i64 = 0,
    licenses: []const []const u8 = &.{},
    depends: []const srcinfo.Dep = &.{},
    provides: []const srcinfo.Dep = &.{},
    conflicts: []const srcinfo.Dep = &.{},
    replaces: []const srcinfo.Dep = &.{},
    /// Config paths pacman preserves across upgrades.
    backup: []const []const u8 = &.{},
    /// Contents of the `install=` scriptlet, stored as `.INSTALL`.
    install_script: ?[]const u8 = null,
    /// `options=()` as declared, recorded in `.BUILDINFO`.
    options: []const []const u8 = &.{},
};

const Entry = struct {
    /// Path relative to $pkgdir, using '/' separators.
    path: []const u8,
    kind: std.Io.File.Kind,
    mode: u32,
    /// Contents, for regular files only.
    data: []const u8 = &.{},
    /// Target, for symlinks only.
    link_target: []const u8 = &.{},
};

/// Collect every member of the staged image.
fn collect(gpa: std.mem.Allocator, io: std.Io, pkgdir: []const u8) ![]Entry {
    var dir = try std.Io.Dir.cwd().openDir(io, pkgdir, .{ .iterate = true });
    defer dir.close(io);

    var entries: std.ArrayList(Entry) = .empty;
    errdefer entries.deinit(gpa);

    var walker = try dir.walk(gpa);
    defer walker.deinit();

    while (try walker.next(io)) |entry| {
        // statFile follows symlinks, so it must not gate their inclusion: a
        // link to a path that does not exist inside $pkgdir would otherwise be
        // silently dropped from the package.
        var mode: u32 = 0o777;
        if (entry.kind != .sym_link) {
            const stat = entry.dir.statFile(io, entry.basename, .{}) catch continue;
            mode = @intCast(@intFromEnum(stat.permissions) & 0o7777);
        }

        const path = try gpa.dupe(u8, entry.path);
        errdefer gpa.free(path);

        var data: []const u8 = &.{};
        var link_target: []const u8 = &.{};
        switch (entry.kind) {
            .file => data = try entry.dir.readFileAlloc(io, entry.basename, gpa, .limited(1 << 31)),
            .sym_link => {
                var link_buf: [std.fs.max_path_bytes]u8 = undefined;
                const len = try entry.dir.readLink(io, entry.basename, &link_buf);
                link_target = try gpa.dupe(u8, link_buf[0..len]);
            },
            else => {},
        }

        try entries.append(gpa, .{
            .path = path,
            .kind = entry.kind,
            .mode = mode,
            .data = data,
            .link_target = link_target,
        });
    }

    return entries.toOwnedSlice(gpa);
}

fn freeEntries(gpa: std.mem.Allocator, entries: []Entry) void {
    for (entries) |e| {
        gpa.free(e.path);
        if (e.data.len > 0) gpa.free(e.data);
        if (e.link_target.len > 0) gpa.free(e.link_target);
    }
    gpa.free(entries);
}

/// Render `.PKGINFO`.
pub fn renderPkginfo(gpa: std.mem.Allocator, meta: Meta, installed_size: u64) ![]u8 {
    var buf: std.Io.Writer.Allocating = .init(gpa);
    errdefer buf.deinit();
    const w = &buf.writer;

    try w.print("# Generated by opti\n", .{});
    try w.print("pkgname = {s}\n", .{meta.pkgname});
    try w.print("pkgbase = {s}\n", .{meta.pkgbase});
    try w.print("pkgver = {s}\n", .{meta.version});
    if (meta.pkgdesc.len > 0) try w.print("pkgdesc = {s}\n", .{meta.pkgdesc});
    if (meta.url.len > 0) try w.print("url = {s}\n", .{meta.url});
    try w.print("builddate = {d}\n", .{meta.builddate});
    try w.print("packager = {s}\n", .{meta.packager});
    try w.print("size = {d}\n", .{installed_size});
    try w.print("arch = {s}\n", .{meta.arch});

    for (meta.licenses) |l| try w.print("license = {s}\n", .{l});
    for (meta.depends) |d| try writeDep(w, "depend", d);
    for (meta.provides) |d| try writeDep(w, "provides", d);
    for (meta.conflicts) |d| try writeDep(w, "conflict", d);
    for (meta.replaces) |d| try writeDep(w, "replaces", d);
    for (meta.backup) |b| try w.print("backup = {s}\n", .{b});

    return buf.toOwnedSlice();
}

/// Render `.BUILDINFO`, the record of how the package was produced.
pub fn renderBuildinfo(gpa: std.mem.Allocator, meta: Meta, builddir: []const u8) ![]u8 {
    var buf: std.Io.Writer.Allocating = .init(gpa);
    errdefer buf.deinit();
    const w = &buf.writer;

    try w.print("format = 2\n", .{});
    try w.print("pkgname = {s}\n", .{meta.pkgname});
    try w.print("pkgbase = {s}\n", .{meta.pkgbase});
    try w.print("pkgver = {s}\n", .{meta.version});
    try w.print("pkgarch = {s}\n", .{meta.arch});
    try w.print("packager = {s}\n", .{meta.packager});
    try w.print("builddate = {d}\n", .{meta.builddate});
    try w.print("builddir = {s}\n", .{builddir});
    try w.print("buildtool = opti\n", .{});
    for (meta.options) |o| try w.print("options = {s}\n", .{o});

    return buf.toOwnedSlice();
}

fn writeDep(w: *std.Io.Writer, key: []const u8, d: srcinfo.Dep) !void {
    if (d.version) |v| {
        try w.print("{s} = {s}{s}{s}\n", .{ key, d.name, d.op.text(), v });
    } else {
        try w.print("{s} = {s}\n", .{ key, d.name });
    }
}

/// Render the mtree listing that pacman-style tooling uses to validate an
/// installed package against its manifest.
fn renderMtree(gpa: std.mem.Allocator, entries: []const Entry) ![]u8 {
    var buf: std.Io.Writer.Allocating = .init(gpa);
    errdefer buf.deinit();
    const w = &buf.writer;

    try w.writeAll("#mtree\n");
    try w.writeAll("/set type=file uid=0 gid=0 mode=644\n");

    var digest_buf: [verify.max_hex_len]u8 = undefined;
    for (entries) |e| {
        switch (e.kind) {
            .directory => try w.print("./{s} type=dir mode={o}\n", .{ e.path, e.mode }),
            .sym_link => try w.print("./{s} type=link link={s}\n", .{ e.path, e.link_target }),
            else => {
                const sha = try verify.hexDigest(.sha256, e.data, &digest_buf);
                try w.print(
                    "./{s} time=0.0 mode={o} size={d} sha256digest={s}\n",
                    .{ e.path, e.mode, e.data.len, sha },
                );
            },
        }
    }

    return buf.toOwnedSlice();
}

/// gzip `data`.
fn gzip(gpa: std.mem.Allocator, data: []const u8) ![]u8 {
    var out: std.Io.Writer.Allocating = try .initCapacity(gpa, 64 * 1024);
    errdefer out.deinit();

    const window = try gpa.alloc(u8, std.compress.flate.max_window_len);
    defer gpa.free(window);

    var comp = try std.compress.flate.Compress.init(&out.writer, window, .gzip, .default);
    try comp.writer.writeAll(data);
    try comp.finish();

    return out.toOwnedSlice();
}

/// Build the package artifact from the staged image at `pkgdir`.
/// Returns the bytes of the finished archive; caller owns them.
pub fn build(
    gpa: std.mem.Allocator,
    io: std.Io,
    pkgdir: []const u8,
    meta: Meta,
    compression: Compression,
    builddir: []const u8,
) ![]u8 {
    const entries = try collect(gpa, io, pkgdir);
    defer freeEntries(gpa, entries);

    if (entries.len == 0) return Error.EmptyPackage;

    var installed_size: u64 = 0;
    for (entries) |e| installed_size += e.data.len;

    const pkginfo = try renderPkginfo(gpa, meta, installed_size);
    defer gpa.free(pkginfo);

    const mtree_text = try renderMtree(gpa, entries);
    defer gpa.free(mtree_text);

    // .MTREE is stored gzipped inside the package regardless of how the
    // package itself is compressed.
    const mtree_gz = try gzip(gpa, mtree_text);
    defer gpa.free(mtree_gz);

    var tar_buf: std.Io.Writer.Allocating = .init(gpa);
    defer tar_buf.deinit();

    var tw: std.tar.Writer = .{ .underlying_writer = &tar_buf.writer };

    const buildinfo = try renderBuildinfo(gpa, meta, builddir);
    defer gpa.free(buildinfo);

    // Metadata members must come first, in this order.
    try tw.writeFileBytes(".PKGINFO", pkginfo, .{ .mode = 0o644 });
    try tw.writeFileBytes(".BUILDINFO", buildinfo, .{ .mode = 0o644 });
    if (meta.install_script) |script| {
        try tw.writeFileBytes(".INSTALL", script, .{ .mode = 0o644 });
    }
    try tw.writeFileBytes(".MTREE", mtree_gz, .{ .mode = 0o644 });

    for (entries) |e| {
        switch (e.kind) {
            .directory => try tw.writeDir(e.path, .{ .mode = e.mode }),
            .sym_link => try tw.writeLink(e.path, e.link_target, .{ .mode = e.mode }),
            else => try tw.writeFileBytes(e.path, e.data, .{ .mode = e.mode }),
        }
    }
    try tw.finishPedantically();

    return switch (compression) {
        .none => tar_buf.toOwnedSlice(),
        .gzip => blk: {
            const raw = try tar_buf.toOwnedSlice();
            defer gpa.free(raw);
            break :blk try gzip(gpa, raw);
        },
    };
}

const testing = std.testing;

test "pkginfo renders required fields" {
    const meta: Meta = .{
        .pkgname = "hello",
        .pkgbase = "hello",
        .version = "2.12.1-1",
        .pkgdesc = "greeting",
        .arch = "x86_64",
    };
    const text = try renderPkginfo(testing.allocator, meta, 4096);
    defer testing.allocator.free(text);

    try testing.expect(std.mem.indexOf(u8, text, "pkgname = hello\n") != null);
    try testing.expect(std.mem.indexOf(u8, text, "pkgver = 2.12.1-1\n") != null);
    try testing.expect(std.mem.indexOf(u8, text, "size = 4096\n") != null);
    try testing.expect(std.mem.indexOf(u8, text, "arch = x86_64\n") != null);
    try testing.expect(std.mem.indexOf(u8, text, "pkgdesc = greeting\n") != null);
}

test "pkginfo renders versioned dependencies" {
    const deps = [_]srcinfo.Dep{
        srcinfo.Dep.parse("glibc"),
        srcinfo.Dep.parse("go>=1.24"),
    };
    const meta: Meta = .{
        .pkgname = "x",
        .pkgbase = "x",
        .version = "1-1",
        .depends = &deps,
    };
    const text = try renderPkginfo(testing.allocator, meta, 0);
    defer testing.allocator.free(text);

    try testing.expect(std.mem.indexOf(u8, text, "depend = glibc\n") != null);
    try testing.expect(std.mem.indexOf(u8, text, "depend = go>=1.24\n") != null);
}

test "gzip round-trips" {
    const original = "hello opti " ** 64;
    const compressed = try gzip(testing.allocator, original);
    defer testing.allocator.free(compressed);

    // gzip magic
    try testing.expectEqual(@as(u8, 0x1f), compressed[0]);
    try testing.expectEqual(@as(u8, 0x8b), compressed[1]);
    try testing.expect(compressed.len < original.len);
}

test "mtree lists files with digests" {
    const entries = [_]Entry{
        .{ .path = "usr", .kind = .directory, .mode = 0o755 },
        .{ .path = "usr/bin/hello", .kind = .file, .mode = 0o755, .data = "abc" },
    };
    const text = try renderMtree(testing.allocator, &entries);
    defer testing.allocator.free(text);

    try testing.expect(std.mem.startsWith(u8, text, "#mtree\n"));
    try testing.expect(std.mem.indexOf(u8, text, "./usr type=dir mode=755\n") != null);
    try testing.expect(std.mem.indexOf(
        u8,
        text,
        "sha256digest=ba7816bf8f01cfea414140de5dae2223b00361a396177a9cb410ff61f20015ad",
    ) != null);
}
